name: Ai issue helper and fixer

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on issue using Pollinations AI
        uses: actions/github-script@v7
        with:
          script: |
            const issueTitle = context.payload.issue.title;
            const issueBody = context.payload.issue.body || '';
            const prompt = `Write a friendly and helpful reply to this GitHub issue:\nTitle: ${issueTitle}\nDescription: ${issueBody}`;

            const response = await fetch("https://text.pollinations.ai/openai/", {
              method: "POST",
              headers: {
                "Content-Type": "application/json"
              },
              body: JSON.stringify({
                model: "openai",
                messages: [{ role: "user", content: prompt }]
              })
            });

            if (!response.ok) {
              throw new Error(`Pollinations API error: ${response.statusText}`);
            }

            const data = await response.json();
            const reply = data.choices?.[0]?.message?.content || "🤖 Sorry, I couldn't generate a response.";

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: reply
            });
