name: AI Issue Helper

on:
  issues:
    types: [opened, edited]

jobs:
  ai_commenter:
    runs-on: ubuntu-latest
    steps:
    - name: Get AI Suggestion
      id: ai
      run: |
        ISSUE_BODY=$(jq -r .issue.body "$GITHUB_EVENT_PATH")
        ISSUE_TITLE=$(jq -r .issue.title "$GITHUB_EVENT_PATH")
        
        echo "Sending to AI..."
        
        RESPONSE=$(curl -s -X POST "https://text.pollinations.ai/openai" \
          -H "Content-Type: application/json" \
          -d "{\"prompt\": \"You are a helpful GitHub bot. An issue was opened with the title: '${ISSUE_TITLE}' and body: '${ISSUE_BODY}'. Suggest a code fix or improvement.\", \"temperature\": 0.5}")

        CLEAN_RESPONSE=$(echo "$RESPONSE" | jq -r '.choices[0].text')

        echo "AI Response: $CLEAN_RESPONSE"

        # Save response for next step
        echo "response<<EOF" >> $GITHUB_ENV
        echo "$CLEAN_RESPONSE" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Comment AI Response on Issue
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issue_number = context.issue.number;
          const body = process.env.response || "AI could not generate a suggestion.";
          github.rest.issues.createComment({
            ...context.repo,
            issue_number,
            body: `🤖 **AI Suggestion:**\n\n${body}`
          });
